/**
 * Memory store maintenance layer (OKF v0.1 conformant).
 *
 * Concept files in entries/*.md are the canonical single source (YAML
 * frontmatter + body). `index.md` is a derived OKF §6 directory-listing
 * regenerated by `rebuild`; `log.md` is the OKF §7 update history. The load
 * path stays Grep-over-index (zero-dependency). This script owns the cold
 * write/refresh/prune path.
 *
 * Naming: concept ID = the leading numeric run of the filename stem. On
 * `rebuild`, a bare-numeric stem (NNN.md) is renamed once to NNN-slug.md,
 * slug derived from the title; stable thereafter — a later title change does
 * NOT re-rename (links and fd-history stay valid). archive/ is never touched
 * by normalization; the NNN prefix makes filename collisions impossible.
 *
 * Frontmatter schema — OKF required/recommended plus agent extensions (EXT,
 * OKF §4.1-permitted):
 *   type            REQUIRED (OKF) — decision | correction
 *   title           OKF recommended — also the slug source on first rebuild
 *   description     OKF recommended — one-sentence actionable core; rebuild
 *                   guards it at ≤ 200 chars (exit 1, index still written)
 *   tags            OKF field
 *   timestamp       OKF field — last meaningful change
 *   last_confirmed  EXT — staleness surface (`stale`)
 *   triggers        EXT — discovery surface (Grep + `query`); rebuild guards
 *                   a minimum of 2 (no upper bound — 5–7 is legitimate)
 *   supersedes      EXT — set only when retiring another concept
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, join, relative, resolve } from "node:path";

const STALE_DEFAULT_DAYS = 180;
const SLUG_MAX_WORDS = 5;
const SLUG_MAX_CHARS = 40;
const DESC_MAX_CHARS = 200;
const TRIGGERS_MIN = 2;
const SLUG_STOPWORDS = new Set([
  "the", "a", "an", "of", "to", "in", "on", "and", "or", "is", "are", "not", "with", "for", "from",
]);
const FM_LINE = /^(\w[\w-]*)\s*:\s*(.*)$/;
const YAML_PLAIN_BAD_START = "-?:,[]{}#&*!|>'\"%@`";

type FmValue = string | string[];

interface Frontmatter {
  [key: string]: FmValue;
}

interface Row {
  id: string;
  stem: string;
  type: string;
  title: string;
  description: string;
  timestamp: string;
  lastConfirmed: string;
  tags: string[];
  triggers: string[];
  supersedes: string;
  file: string;
  fm: Frontmatter;
  body: string;
}

/**
 * Resolve the repo knowledge base: `<git-toplevel>/memory`.
 *
 * Walks up from CWD for a `.git` marker; falls back to `./memory` (the
 * conventional repo-root layout). The script lives in
 * `.agents/skills/memory/`, so its own dir is NOT the KB — never default to
 * the script's parent. Override with `--root` to target an alternate store.
 */
function defaultRoot(): string {
  let cur = process.cwd();
  for (;;) {
    if (existsSync(join(cur, ".git"))) return join(cur, "memory");
    const parent = dirname(cur);
    if (parent === cur) return join(process.cwd(), "memory");
    cur = parent;
  }
}

let ROOT = defaultRoot();

function entriesDir(): string {
  return join(ROOT, "entries");
}

function archiveDir(): string {
  return join(ROOT, "archive");
}

function indexPath(): string {
  return join(ROOT, "index.md");
}

function logPath(): string {
  return join(ROOT, "log.md");
}

/** Print a warning line to stderr. */
function warn(msg: string): void {
  console.error(`warn: ${msg}`);
}

/** Normalize an unknown thrown value to a message string. */
function errorMessage(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

/** Expand a leading `~` to the home directory (argparse `expanduser` parity). */
function expandUser(p: string): string {
  if (p === "~") return homedir();
  if (p.startsWith("~/")) return join(homedir(), p.slice(2));
  return p;
}

/** Point every path helper at `--root` (resolved absolute). */
function applyRoot(rootArg: string): void {
  if (!rootArg) return;
  ROOT = resolve(expandUser(rootArg));
}

/** Local calendar date as `YYYY-MM-DD` (not UTC). */
function isoDate(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

/** Today's local date as `YYYY-MM-DD`. */
function isoToday(): string {
  return isoDate(new Date());
}

/** Local midnight of the current date. */
function todayLocal(): Date {
  const n = new Date();
  return new Date(n.getFullYear(), n.getMonth(), n.getDate());
}

/**
 * Parse a strict `YYYY-MM-DD` string as a LOCAL date; null when malformed or
 * non-calendar (Python `date.fromisoformat` + ValueError parity).
 */
function parseLocalDate(s: string): Date | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(s);
  if (!m) return null;
  const y = Number(m[1]);
  const mo = Number(m[2]) - 1;
  const d = Number(m[3]);
  const dt = new Date(y, mo, d);
  if (dt.getFullYear() !== y || dt.getMonth() !== mo || dt.getDate() !== d) return null;
  return dt;
}

/** Whole-day difference between two local midnights. */
function dayDiff(a: Date, b: Date): number {
  return Math.round((a.getTime() - b.getTime()) / 86_400_000);
}

/** Resolve backslash-escapes inside a double-quoted YAML scalar. */
function unescapeDoubleQuoted(s: string): string {
  let out = "";
  let i = 0;
  while (i < s.length) {
    const c = s.charAt(i);
    if (c === "\\" && i + 1 < s.length && (s.charAt(i + 1) === '"' || s.charAt(i + 1) === "\\")) {
      out += s.charAt(i + 1);
      i += 2;
      continue;
    }
    out += c;
    i++;
  }
  return out;
}

/**
 * Plain-scalar safety: quote if empty, starts with a YAML indicator, ends
 * with a space, or contains `": "` / `" #"` (would mis-parse as a mapping).
 */
function needsQuote(v: string): boolean {
  if (v === "" || YAML_PLAIN_BAD_START.includes(v.charAt(0)) || v.endsWith(" ")) return true;
  return v.includes(": ") || v.includes(" #");
}

/** Serialize a scalar as a YAML plain scalar, double-quoted when unsafe. */
function yamlStr(v: string): string {
  if (needsQuote(v)) return `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  return v;
}

/** Parse a concept file into its frontmatter map and body. */
function parseFrontmatter(text: string): { fm: Frontmatter; body: string } {
  const lines = text.split(/\r?\n/);
  if (lines[0]?.trim() !== "---") return { fm: {}, body: text };
  let end = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i]?.trim() === "---") {
      end = i;
      break;
    }
  }
  if (end === -1) return { fm: {}, body: text };
  const fm: Frontmatter = {};
  for (const ln of lines.slice(1, end)) {
    const s = ln.trim();
    if (!s || s.startsWith("#")) continue;
    const m = FM_LINE.exec(s);
    if (!m?.[1] || m[2] === undefined) continue;
    let val: FmValue = m[2].trim();
    if (val.startsWith("[") && val.endsWith("]")) {
      const inner = val.slice(1, -1).trim();
      val = inner ? inner.split(",").map((x) => x.trim()).filter((x) => x !== "") : [];
    } else if (
      val.length >= 2 &&
      (val.charAt(0) === '"' || val.charAt(0) === "'") &&
      val.charAt(0) === val.charAt(val.length - 1)
    ) {
      val = val.charAt(0) === '"' ? unescapeDoubleQuoted(val.slice(1, -1)) : val.slice(1, -1);
    }
    fm[m[1]] = val;
  }
  const body = lines.slice(end + 1).join("\n").replace(/^\n+/, "");
  return { fm, body };
}

/** Serialize a frontmatter map back to its `---`-fenced block (LF, key order preserved). */
function serializeFrontmatter(fm: Frontmatter): string {
  const out = ["---"];
  for (const [k, v] of Object.entries(fm)) {
    if (Array.isArray(v)) out.push(`${k}: [${v.join(", ")}]`);
    else out.push(`${k}: ${yamlStr(v)}`);
  }
  out.push("---");
  return out.join("\n");
}

/** Coerce a frontmatter value to a string list (bare string → singleton). */
function asList(v: FmValue | undefined): string[] {
  if (Array.isArray(v)) return v;
  if (v === undefined || v === "") return [];
  return [v];
}

/** Concept ID = the leading numeric run of the stem (else the stem itself). */
function numericId(stem: string): string {
  return /^\d+/.exec(stem)?.[0] ?? stem;
}

/** Load every concept file in a dir as a row (sorted by filename; unreadable/typeless skipped with a warning). */
function loadDir(dir: string): Row[] {
  if (!existsSync(dir)) return [];
  const rows: Row[] = [];
  for (const name of readdirSync(dir).filter((f) => f.endsWith(".md")).sort()) {
    const file = join(dir, name);
    let text: string;
    try {
      text = readFileSync(file, "utf-8");
    } catch (e) {
      warn(`unreadable ${file}: ${errorMessage(e)}`);
      continue;
    }
    const { fm, body } = parseFrontmatter(text);
    if (!("type" in fm)) {
      warn(`no type in frontmatter: ${relative(ROOT, file)}`);
      continue;
    }
    const stem = name.slice(0, -3);
    rows.push({
      id: numericId(stem),
      stem,
      type: String(fm["type"] ?? ""),
      title: String(fm["title"] ?? ""),
      description: String(fm["description"] ?? ""),
      timestamp: String(fm["timestamp"] ?? ""),
      lastConfirmed: String(fm["last_confirmed"] ?? ""),
      tags: asList(fm["tags"]),
      triggers: asList(fm["triggers"]),
      supersedes: fm["supersedes"] !== undefined ? String(fm["supersedes"]) : "",
      file,
      fm,
      body,
    });
  }
  return rows;
}

/** Find a row by full stem, exact ID, or numeric ID with leading-zero tolerance. */
function findRow(rows: Row[], want: string): Row | undefined {
  const wantNum = /^\d+/.exec(want)?.[0];
  for (const r of rows) {
    if (r.stem === want || r.id === want) return r;
    const idNum = /^\d+/.exec(r.id)?.[0];
    if (idNum !== undefined && wantNum !== undefined && stripZeros(idNum) === stripZeros(wantNum)) return r;
  }
  return undefined;
}

/** Strip leading zeros (Python `lstrip("0")` parity for ID comparison). */
function stripZeros(s: string): string {
  return s.replace(/^0+/, "");
}

/**
 * Derive the filename slug from a title: lowercase kebab-case over
 * alphanumeric words, trivial stopwords dropped, first 5 words kept, capped
 * at ~40 chars on a word boundary. Empty when nothing survives.
 */
function slugify(title: string): string {
  const words = title
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((w) => w !== "" && !SLUG_STOPWORDS.has(w));
  let slug = words.slice(0, SLUG_MAX_WORDS).join("-");
  if (slug.length > SLUG_MAX_CHARS) {
    slug = slug.slice(0, SLUG_MAX_CHARS);
    const boundary = slug.lastIndexOf("-");
    if (boundary > 0) slug = slug.slice(0, boundary);
  }
  return slug;
}

/**
 * Rename bare-numeric stems to `NNN-slug.md` (slug from the title, derived
 * ONCE — already-slugged names are stable; empty-title fallback keeps the
 * numeric-only name). archive/ is never touched.
 */
function normalizeNames(rows: Row[]): void {
  for (const r of rows) {
    if (!/^\d+$/.test(r.stem)) continue;
    const slug = slugify(r.title);
    if (slug === "") continue;
    const dest = join(entriesDir(), `${r.stem}-${slug}.md`);
    if (existsSync(dest)) {
      warn(`rename skipped, target exists: entries/${r.stem}-${slug}.md`);
      continue;
    }
    renameSync(r.file, dest);
    console.log(`renamed entries/${r.stem}.md → entries/${r.stem}-${slug}.md`);
  }
}

/**
 * Regenerate `index.md` (OKF §6 listing): normalize names, guard the schema
 * (description ≤ 200 chars, triggers ≥ 2), write one slim line per concept.
 * The index is written even when guards fail — the derived artifact never
 * goes stale behind a failed gate; violations exit 1.
 */
function cmdRebuild(): number {
  normalizeNames(loadDir(entriesDir()));
  const rows = loadDir(entriesDir()).sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const violations: string[] = [];
  for (const r of rows) {
    if (r.description.length > DESC_MAX_CHARS) {
      violations.push(`${r.stem}: description is ${r.description.length} chars (max ${DESC_MAX_CHARS})`);
    }
    if (r.triggers.length < TRIGGERS_MIN) {
      violations.push(`${r.stem}: ${r.triggers.length} trigger(s) (min ${TRIGGERS_MIN})`);
    }
  }
  const out = [
    "---",
    'okf_version: "0.1"',
    "---",
    "# Memory Index",
    "",
    "<!-- DO NOT EDIT — regenerated by `bun .agents/skills/memory/memory.ts rebuild` (script at .agents/skills/memory/memory.ts). " +
      "Each line carries the concept's id-slug, title, and triggers for Grep; description/tags/type live in the entry's frontmatter. -->",
    "",
    "OKF v0.1 bundle. Active concepts in `entries/`; retired in `archive/` (not listed). " +
      "Query path: Grep THIS file for a keyword → Read the matched concept.",
    "",
  ];
  for (const r of rows) {
    const title = r.title || r.id;
    const triggers = r.triggers.join(", ") || "—";
    out.push(`* [${r.stem} — ${title}](entries/${r.stem}.md) · \`triggers: ${triggers}\``);
  }
  out.push("");
  writeFileSync(indexPath(), out.join("\n"), "utf-8");
  console.log(`rebuilt index.md (${rows.length} active concepts)`);
  for (const v of violations) warn(`schema violation — ${v}`);
  return violations.length ? 1 : 0;
}

/**
 * Allocate the next free 3-digit ID. Archive IDs are retired — never
 * reallocate them, or a new live entry collides with archive/NNN and its
 * supersession narrative.
 */
function nextId(): string {
  const used = new Set<string>();
  for (const r of loadDir(entriesDir())) used.add(r.id);
  for (const r of loadDir(archiveDir())) used.add(r.id);
  let n = 1;
  while (used.has(String(n).padStart(3, "0"))) n++;
  return String(n).padStart(3, "0");
}

/**
 * Append a dated bullet to `log.md` (OKF §7), newest date first. Bullets are
 * the stripped lines; history is rewritten in place, never reordered.
 */
function appendLog(msg: string, label: string): void {
  const today = isoToday();
  const bullet = `* **${label}**: ${msg}`;
  const sections = new Map<string, string[]>();
  const order: string[] = [];
  if (existsSync(logPath())) {
    let cur: string | null = null;
    for (const ln of readFileSync(logPath(), "utf-8").split(/\r?\n/)) {
      const s = ln.trim();
      if (s.startsWith("## ")) {
        cur = s.slice(3).trim();
        if (!sections.has(cur)) {
          sections.set(cur, []);
          order.push(cur);
        }
      } else if (cur !== null && s.startsWith("* ")) {
        sections.get(cur)?.push(s);
      }
    }
  }
  if (!sections.has(today)) {
    sections.set(today, []);
    order.unshift(today);
  }
  sections.get(today)?.push(bullet);
  const out = ["# Memory Update Log", ""];
  for (const d of order) {
    out.push(`## ${d}`);
    out.push(...(sections.get(d) ?? []));
    out.push("");
  }
  writeFileSync(logPath(), `${out.join("\n").replace(/\n+$/, "")}\n`, "utf-8");
}

/** Allocate the next ID and write a concept template (bare `NNN.md`; the first rebuild assigns its slug). */
function cmdAdd(fix: boolean): number {
  mkdirSync(entriesDir(), { recursive: true });
  const nid = nextId();
  const today = isoToday();
  const conceptType = fix ? "correction" : "decision";
  const fm: Frontmatter = {
    type: conceptType,
    title: "Imperative title (the rule/fact itself)",
    description: "One-sentence actionable core — what loads by default.",
    tags: [],
    timestamp: today,
    last_confirmed: today,
    triggers: [],
  };
  const body =
    "# Why\n\n" +
    "Rationale / alternatives / what breaks if ignored.\n\n" +
    "# Evidence\n\n" +
    "Source citation, the passing command, or the error it fixes.\n";
  const file = join(entriesDir(), `${nid}.md`);
  writeFileSync(file, `${serializeFrontmatter(fm)}\n${body}`, "utf-8");
  appendLog(`Added concept [${nid}](entries/${nid}.md) (type: ${conceptType}).`, "Creation");
  console.log(relative(ROOT, file));
  return 0;
}

/** List concepts with `last_confirmed` older than N days, oldest first. */
function cmdStale(days: number): number {
  const today = todayLocal();
  const cutoff = new Date(today.getFullYear(), today.getMonth(), today.getDate() - days);
  const found: Array<{ age: number; row: Row }> = [];
  for (const r of loadDir(entriesDir())) {
    const lc = parseLocalDate(r.lastConfirmed);
    if (!lc) {
      warn(`bad last_confirmed in ${r.id}: '${r.lastConfirmed}'`);
      continue;
    }
    if (lc < cutoff) found.push({ age: dayDiff(today, lc), row: r });
  }
  found.sort((a, b) => b.age - a.age);
  if (found.length === 0) {
    console.log(`no concepts older than ${days} days`);
    return 0;
  }
  for (const { age, row } of found) {
    console.log(`${row.id}  age=${age}d  last_confirmed=${row.lastConfirmed}  ${relative(ROOT, row.file)}`);
  }
  return 0;
}

/** Print store counts: active/archive/orphans, by type, by tag, oldest active. */
function cmdStats(): number {
  const active = loadDir(entriesDir());
  const archived = loadDir(archiveDir());
  const ref = new Set(active.filter((r) => r.supersedes !== "").map((r) => r.supersedes));
  const orphans = archived.filter((r) => !ref.has(r.id));
  console.log(`active: ${active.length}`);
  console.log(`archive: ${archived.length}`);
  console.log(`archive orphans (prunable): ${orphans.length}`);
  const typec = new Map<string, number>();
  for (const r of active) typec.set(r.type, (typec.get(r.type) ?? 0) + 1);
  const typeLine = [...typec.entries()].sort(([a], [b]) => (a < b ? -1 : 1)).map(([k, v]) => `${k}=${v}`).join(", ");
  console.log(`by type: ${typeLine || "—"}`);
  const tagc = new Map<string, number>();
  for (const r of active) {
    for (const t of r.tags) tagc.set(t, (tagc.get(t) ?? 0) + 1);
  }
  const tagLine = [...tagc.entries()].sort(([a], [b]) => (a < b ? -1 : 1)).map(([t, c]) => `${t}=${c}`).join(", ");
  console.log(`by tag: ${tagLine || "—"}`);
  if (active.length > 0) {
    let oldest = active[0] as Row;
    for (const r of active) {
      if ((r.lastConfirmed || "9") < (oldest.lastConfirmed || "9")) oldest = r;
    }
    console.log(`oldest active: ${oldest.id} (last_confirmed=${oldest.lastConfirmed})`);
  }
  return 0;
}

/** Archive `<old>`; mark `<new>` as superseding it; rebuild. */
function cmdSupersede(oldId: string, newId: string): number {
  const active = loadDir(entriesDir());
  const oldRow = findRow(active, oldId);
  if (!oldRow) {
    console.error(`error: active concept ${oldId} not found`);
    return 1;
  }
  const newRow = findRow(active, newId);
  if (!newRow) {
    console.error(`error: active concept ${newId} not found`);
    return 1;
  }
  if (oldRow.id === newRow.id) {
    console.error("error: old and new are the same concept");
    return 1;
  }
  mkdirSync(archiveDir(), { recursive: true });
  const dest = join(archiveDir(), basename(oldRow.file));
  renameSync(oldRow.file, dest);
  const newFm: Frontmatter = { ...newRow.fm, supersedes: oldRow.id };
  writeFileSync(newRow.file, `${serializeFrontmatter(newFm)}\n${newRow.body}`, "utf-8");
  appendLog(
    `Archived [${oldRow.id}](archive/${basename(oldRow.file)}) → superseded by [${newRow.id}](entries/${newRow.stem}.md).`,
    "Deprecation"
  );
  console.log(`archived ${oldRow.id} → ${relative(ROOT, dest)}; ${newRow.id} supersedes it`);
  return cmdRebuild();
}

/** List (dry-run) or delete (`--apply`) archive entries referenced by no active concept. */
function cmdPrune(apply: boolean): number {
  const active = loadDir(entriesDir());
  const archived = loadDir(archiveDir());
  const ref = new Set(active.filter((r) => r.supersedes !== "").map((r) => r.supersedes));
  const orphans = archived.filter((r) => !ref.has(r.id));
  if (orphans.length === 0) {
    console.log("no orphaned archive entries");
    return 0;
  }
  for (const r of orphans) {
    const rel = relative(ROOT, r.file);
    if (apply) {
      unlinkSync(r.file);
      console.log(`deleted ${rel}`);
    } else {
      console.log(`orphan ${rel}  (use --apply to delete)`);
    }
  }
  return apply ? cmdRebuild() : 0;
}

/** Scan entry frontmatter for a keyword; print ranked titles + descriptions. */
function cmdQuery(keyword: string): number {
  const kw = keyword.toLowerCase();
  const scored: Array<{ score: number; row: Row }> = [];
  for (const r of loadDir(entriesDir())) {
    let score = 0;
    if (r.triggers.some((t) => t.toLowerCase().includes(kw))) score += 4;
    if (r.tags.some((t) => t.toLowerCase().includes(kw))) score += 3;
    if (r.title.toLowerCase().includes(kw)) score += 2;
    if (r.description.toLowerCase().includes(kw)) score += 1;
    if (score > 0) scored.push({ score, row: r });
  }
  scored.sort((a, b) => b.score - a.score);
  if (scored.length === 0) {
    console.log(`no matches for '${kw}'`);
    return 0;
  }
  for (const { score, row } of scored) {
    console.log(`--- ${row.id} (score=${score}) ${relative(ROOT, row.file)} ---`);
    console.log(`# ${row.title}`);
    console.log(row.description);
    console.log("");
  }
  return 0;
}

/** Append a dated, labeled line to `log.md`. */
function cmdLog(message: string, label: string): number {
  appendLog(message, label);
  console.log(`appended to ${relative(ROOT, logPath())}`);
  return 0;
}

/** Print usage to stderr and exit 2 (argparse parity). */
function usage(): never {
  console.error(
    "usage: bun .agents/skills/memory/memory.ts [--root <dir>] <command> [args]\n" +
      "commands: rebuild | add [--fix] | stale [days] | stats | supersede <old> <new> |\n" +
      "          prune [--apply] | query <keyword> | log <message> [--label <label>]"
  );
  process.exit(2);
}

/** Parse a strict non-negative integer CLI positional (argparse `type=int` parity). */
function parseDays(s: string): number {
  const n = Number(s);
  if (!Number.isInteger(n)) usage();
  return n;
}

/** Assert every arg is the given boolean flag; report whether it appeared. */
function booleanFlag(args: string[], name: string): boolean {
  let seen = false;
  for (const a of args) {
    if (a === name) seen = true;
    else usage();
  }
  return seen;
}

/** Parse `log` args: one positional message plus an optional `--label <v>` / `--label=<v>`. */
function parseLogArgs(args: string[]): { message: string; label: string } {
  let label = "Update";
  const pos: string[] = [];
  for (let i = 0; i < args.length; i++) {
    const a = args[i] ?? "";
    if (a === "--label") label = args[++i] ?? usage();
    else if (a.startsWith("--label=")) label = a.slice("--label=".length);
    else pos.push(a);
  }
  if (pos.length !== 1) usage();
  return { message: pos[0] ?? "", label };
}

/** CLI entry: extract the global `--root`, dispatch the subcommand, return its exit code. */
function main(): number {
  const argv = process.argv.slice(2);
  let rootArg = "";
  const tokens: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i] ?? "";
    if (a === "--root") {
      rootArg = argv[++i] ?? usage();
    } else if (a.startsWith("--root=")) {
      rootArg = a.slice("--root=".length);
    } else {
      tokens.push(a);
    }
  }
  applyRoot(rootArg);
  const cmd = tokens.shift();
  const rest = tokens;
  switch (cmd) {
    case "rebuild":
      if (rest.length > 0) usage();
      return cmdRebuild();
    case "add":
      return cmdAdd(booleanFlag(rest, "--fix"));
    case "stale": {
      if (rest.length > 1) usage();
      const days = rest.length === 1 ? parseDays(rest[0] ?? "") : STALE_DEFAULT_DAYS;
      return cmdStale(days);
    }
    case "stats":
      if (rest.length > 0) usage();
      return cmdStats();
    case "supersede": {
      if (rest.length !== 2) usage();
      return cmdSupersede(rest[0] ?? "", rest[1] ?? "");
    }
    case "prune":
      return cmdPrune(booleanFlag(rest, "--apply"));
    case "query": {
      if (rest.length !== 1) usage();
      return cmdQuery(rest[0] ?? "");
    }
    case "log": {
      const { message, label } = parseLogArgs(rest);
      return cmdLog(message, label);
    }
    default:
      usage();
  }
}

try {
  process.exit(main());
} catch (e) {
  console.error(`error: ${errorMessage(e)}`);
  process.exit(1);
}
