[test]
preload = "./utils/happydom.js"

coveragePathIgnorePatterns = [
  "**/lib/**/**.ts",
  "utils/**.**",
  "!{**/**/dist/bundle.js,**/**/dist/index.js,**/**/dist/registry/**/*.js,**/plugins/**/**.mjs}"
]