export const navigation = {
  learn: [
    "Quick-Start",
    {
      Concepts: [
        "Reactivity",
        "Templates",
        "Attribute-Prefixes",
        "Components",
        "Control-Flow",
        "Styling",
        "State",
        "Routing",
        "Resources",
        "Error-Handling",
        "Reactive-Refs",
        "Custom-Elements",
        "SSR",
        "Hydration",
        "Headless-Behaviors",
      ],
    },
    {
      Patterns: [
        "Reactivity",
        "Rendering",
        "Styling",
        "State",
        "Routing",
        "Resource",
        "SSR",
        "Testing",
      ],
    },
    {
      "Tutorials": [
        "Counter",
        "Theme-Switcher",
        "Todo",
        "Blog",
        "SSR-Islands",
        "SSR-Routing",
        "SSR-Streaming",
        "Astro-Islands",
      ],
    }
  ],
  components: ["Button", "Input", "Card", "Dialog", "Tabs", "Badge", "Alert", "Kbd", "Separator", "Skeleton", "Spinner", "Empty", "Label", "Textarea", "Native-Select", "Aspect-Ratio", "Avatar", "Progress", "Table", "Button-Group", "Input-Group", "Field", "Pagination", "Item", "Marker", "Direction", "Bubble", "Message", "Message-Scroller", "Attachment", "Collapsible", "Accordion", "Checkbox", "Radio-Group", "Switch", "Toggle", "Toggle-Group", "Slider", "Resizable", "Tooltip", "Hover-Card", "Popover", "Dropdown-Menu", "Context-Menu", "Menubar", "Navigation-Menu", "Breadcrumb", "Select", "Combobox", "Command", "Alert-Dialog", "Sheet", "Drawer", "Sonner", "Scroll-Area", "Calendar", "Input-Otp", "Form", "Sidebar"],
  reference: [
    { core: ["signal", "signalArray", "signalMap", "signalSet", "computed", "effect", "batch", "scope", "untracked", "flush"] },
    {
      dom: [
        { label: "on:", slug: "on" },
        { label: "e:", slug: "e" },
        { label: "hook:", slug: "hook" },
        { label: "error:", slug: "error" },
        "mount",
        "hydrate",
        "element",
        "html",
        "raw",
        "ForEach",
        "Portal",
        "Lazy",
        "Transition",
        "Suspense",
        "onError",
        "$ref",
        "$collection",
        "component",
        "registry",
        "behaviors",
      ]
    },
    { css: ["css", "style", "cva", "cx", "vars", "keyframes", "cssText", "removeCss", "removeStyle", "removeVars", "removeKeyframes", "resetCss", "resetVars"] },
    { store: ["store", "persiststore", "localstorageadaptor", "sessionstorageadaptor"] },
    { router: ["router", "route", "navigate", "href", "resetrouter"] },
    { resource: ["resource", "resourcecache", "resetresource"] },
    { ssr: ["ssr", "doc"] },
  ],
  plugins: ["babel", "rollup", "vite", "astro"],
} as const;