export const navigation = {
  learn: [
    "Quick-Start",
    {
      Concepts: [
        "Reactivity",
        "Templates",
        "Attribute-Prefixes",
        "Components",
        "Control-Flow",
        "ForEach",
        "Styling",
        "State",
        "Routing",
        "Route-Hooks",
        "Resources",
        "Error-Handling",
        "Reactive-Refs",
        "Custom-Elements",
        "SSR",
        "Hydration",
      ],
    },
    {
      Patterns: [
        "Reactivity",
        "Rendering",
        "Styling",
        "State",
        "Routing",
        "Routing-SSR",
        "Resource",
        "SSR",
        "Testing",
      ],
    },
    {
      "Tutorials": [
        "Counter",
        "Theme-Switcher",
        "Todo",
        "Blog",
        "SSR-Islands",
        "SSR-Routing",
        "SSR-Streaming",
      ],
    }
  ],
  reference: [
    { core: ["signal", "computed", "effect", "batch", "scope", "untracked"] },
    {
      dom: [
        { label: "on:", slug: "on" },
        { label: "e:", slug: "e" },
        { label: "hook:", slug: "hook" },
        { label: "error:", slug: "error" },
        "mount",
        "hydrate",
        "element",
        "html",
        "raw",
        "ForEach",
        "Portal",
        "Lazy",
        "Transition",
        "Suspense",
        "onError",
        "$ref",
        "$collection",
        "component",
        "registry",
      ]
    },
    { css: ["css", "cssVars", "removeCss", "resetCss", "removeCssVars", "resetCssVars"] },
    { store: ["store"] },
    { router: ["router", "route", "navigate", "resetrouter"] },
    { resource: ["resource", "resourcecache", "resetresource"] },
    { ssr: ["ssr", "doc"] },
  ],
  plugins: ["babel", "rollup", "vite", "astro"],
} as const;