#!/usr/bin/env python3
"""Memory store maintenance layer (OKF v0.1 conformant).

Concept files in entries/*.md are the canonical single source (YAML frontmatter
+ body). `index.md` is a derived OKF §6 directory-listing regenerated by
`rebuild`; `log.md` is the OKF §7 update history. The load path stays
Grep-over-index (zero-dependency). This script owns the cold
write/refresh/prune path.

Frontmatter schema — OKF required/recommended plus agent extensions (EXT,
OKF §4.1-permitted):
  type            REQUIRED (OKF) — decision | correction
  title           OKF recommended
  description     OKF recommended — the one-line actionable core
  tags            OKF field
  timestamp       OKF field — last meaningful change
  last_confirmed  EXT — staleness surface (`stale`)
  triggers        EXT — discovery surface (Grep + `query`)
  supersedes      EXT — set only when retiring another concept
Concept ID = filename stem (OKF: the file path without `.md`).
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True


def _default_root() -> Path:
    """Resolve the repo knowledge base: <git-toplevel>/memory.

    Walks up from CWD for a `.git` marker; falls back to ./memory (the
    conventional repo-root layout). The script lives in .agents/skills/brain-memory/,
    so its own dir is NOT the KB — never default to __file__.parent. Override
    with --root to target an alternate store.
    """
    cwd = Path.cwd()
    for base in (cwd, *cwd.parents):
        if (base / ".git").exists():
            return base / "memory"
    return cwd / "memory"


ROOT = _default_root()
ENTRIES = ROOT / "entries"
ARCHIVE = ROOT / "archive"
INDEX = ROOT / "index.md"
LOG = ROOT / "log.md"
STALE_DEFAULT_DAYS = 180

_FM_LINE = re.compile(r"^(\w[\w-]*)\s*:\s*(.*)$")


def warn(msg: str) -> None:
    print(f"warn: {msg}", file=sys.stderr)


_YAML_PLAIN_BAD_START = set("-?:,[]{}#&*!|>'\"%@" + "`")


def _unescape(s: str) -> str:
    out = []
    i = 0
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s) and s[i + 1] in ('"', "\\"):
            out.append(s[i + 1])
            i += 2
            continue
        out.append(s[i])
        i += 1
    return "".join(out)


def _needs_quote(v: str) -> bool:
    # Plain-scalar safety: quote if empty, starts with a YAML indicator, ends
    # with space, or contains ": " / " #" (would mis-parse as a mapping).
    if v == "" or v[0] in _YAML_PLAIN_BAD_START or v[-1] == " ":
        return True
    if ": " in v or " #" in v:
        return True
    return False


def _yaml_str(v: str) -> str:
    if _needs_quote(v):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return v


def parse_frontmatter(text: str) -> tuple[dict, str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return {}, text
    fm: dict = {}
    for ln in lines[1:end]:
        s = ln.strip()
        if not s or s.startswith("#"):
            continue
        m = _FM_LINE.match(s)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            val = [x.strip() for x in inner.split(",") if x.strip()] if inner else []
        elif len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
            val = _unescape(val[1:-1]) if val[0] == '"' else val[1:-1]
        fm[key] = val
    body = "\n".join(lines[end + 1:]).lstrip("\n")
    return fm, body


def serialize_frontmatter(fm: dict) -> str:
    out = ["---"]
    for k, v in fm.items():
        if isinstance(v, list):
            out.append(f"{k}: [{', '.join(v)}]")
        else:
            out.append(f"{k}: {_yaml_str(str(v))}")
    out.append("---")
    return "\n".join(out)


def _as_list(v) -> list[str]:
    if isinstance(v, list):
        return v
    if v in ("", None):
        return []
    return [str(v)]


def _load_dir(d: Path) -> list[dict]:
    if not d.exists():
        return []
    rows = []
    for p in sorted(d.glob("*.md")):
        try:
            text = p.read_text(encoding="utf-8")
        except OSError as e:
            warn(f"unreadable {p}: {e}")
            continue
        fm, body = parse_frontmatter(text)
        if "type" not in fm:
            warn(f"no type in frontmatter: {p.relative_to(ROOT)}")
            continue
        rows.append(
            {
                "id": p.stem,
                "type": str(fm.get("type", "")),
                "title": str(fm.get("title", "")),
                "description": str(fm.get("description", "")),
                "timestamp": str(fm.get("timestamp", "")),
                "last_confirmed": str(fm.get("last_confirmed", "")),
                "tags": _as_list(fm.get("tags")),
                "triggers": _as_list(fm.get("triggers")),
                "supersedes": str(fm["supersedes"]) if "supersedes" in fm else "",
                "file": p,
                "fm": fm,
                "body": body,
            }
        )
    return rows


def _find(rows: list[dict], want: str) -> dict | None:
    for r in rows:
        if r["id"] == want or r["id"].lstrip("0") == want.lstrip("0"):
            return r
    return None


def _append_log(msg: str, label: str = "Update") -> None:
    """Append a dated bullet to log.md (OKF §7), newest date first."""
    today = dt.date.today().isoformat()
    bullet = f"* **{label}**: {msg}"
    sections: dict[str, list[str]] = {}
    order: list[str] = []
    if LOG.exists():
        cur_date = None
        for ln in LOG.read_text(encoding="utf-8").splitlines():
            s = ln.strip()
            if s.startswith("## "):
                cur_date = s[3:].strip()
                sections.setdefault(cur_date, [])
                if cur_date not in order:
                    order.append(cur_date)
            elif cur_date is not None and s.startswith("* "):
                sections[cur_date].append(s)
    if today not in sections:
        sections[today] = []
        order.insert(0, today)
    sections[today].append(bullet)
    out = ["# Memory Update Log", ""]
    for d in order:
        out.append(f"## {d}")
        out.extend(sections[d])
        out.append("")
    LOG.write_text("\n".join(out).rstrip("\n") + "\n", encoding="utf-8")


def cmd_rebuild(args) -> int:
    rows = _load_dir(ENTRIES)
    rows.sort(key=lambda r: r["id"])
    out = [
        "---",
        'okf_version: "0.1"',
        "---",
        "# Memory Index",
        "",
        "<!-- DO NOT EDIT — regenerated by `python3 memory.py rebuild` (script at .agents/skills/brain-memory/memory.py). "
        "Each line carries the concept's description + triggers/tags/type inline for Grep. -->",
        "",
        "OKF v0.1 bundle. Active concepts in `entries/`; retired in `archive/` (not listed). "
        "Query path: Grep THIS file for a keyword → Read the matched concept.",
        "",
    ]
    for r in rows:
        rel = r["file"].relative_to(ROOT).as_posix()
        triggers = ", ".join(r["triggers"]) or "—"
        tags = ", ".join(r["tags"]) or "—"
        desc = r["description"] or "(no description)"
        title = r["title"] or r["id"]
        out.append(
            f"* [{r['id']} — {title}]({rel}) — {desc} "
            f"· `triggers: {triggers}` · `tags: {tags}` · `type: {r['type']}`"
        )
    out.append("")
    INDEX.write_text("\n".join(out), encoding="utf-8")
    print(f"rebuilt index.md ({len(rows)} active concepts)")
    return 0


def _next_id() -> str:
    used = {r["id"] for r in _load_dir(ENTRIES)}
    n = 1
    while f"{n:03d}" in used:
        n += 1
    return f"{n:03d}"


def cmd_add(args) -> int:
    ENTRIES.mkdir(parents=True, exist_ok=True)
    nid = _next_id()
    today = dt.date.today().isoformat()
    concept_type = "correction" if args.fix else "decision"
    fm = {
        "type": concept_type,
        "title": "Imperative title (the rule/fact itself)",
        "description": "One-sentence actionable core — what loads by default.",
        "tags": [],
        "timestamp": today,
        "last_confirmed": today,
        "triggers": [],
    }
    body = (
        "# Why\n\n"
        "Rationale / alternatives / what breaks if ignored.\n\n"
        "# Evidence\n\n"
        "Source citation, the passing command, or the error it fixes.\n"
    )
    path = ENTRIES / f"{nid}.md"
    path.write_text(serialize_frontmatter(fm) + "\n" + body, encoding="utf-8")
    _append_log(
        f"Added concept [{nid}](entries/{nid}.md) (type: {concept_type}).",
        "Creation",
    )
    print(str(path.relative_to(ROOT)))
    return 0


def cmd_stale(args) -> int:
    cutoff = dt.date.today() - dt.timedelta(days=args.days)
    today = dt.date.today()
    found = []
    for r in _load_dir(ENTRIES):
        try:
            lc = dt.date.fromisoformat(r["last_confirmed"])
        except ValueError:
            warn(f"bad last_confirmed in {r['id']}: {r['last_confirmed']!r}")
            continue
        if lc < cutoff:
            found.append(((today - lc).days, r))
    found.sort(key=lambda x: -x[0])
    if not found:
        print(f"no concepts older than {args.days} days")
        return 0
    for age, r in found:
        print(
            f"{r['id']}  age={age}d  last_confirmed={r['last_confirmed']}  "
            f"{r['file'].relative_to(ROOT)}"
        )
    return 0


def cmd_stats(args) -> int:
    active = _load_dir(ENTRIES)
    archived = _load_dir(ARCHIVE)
    ref = {r["supersedes"] for r in active if r["supersedes"]}
    orphans = [r for r in archived if r["id"] not in ref]
    print(f"active: {len(active)}")
    print(f"archive: {len(archived)}")
    print(f"archive orphans (prunable): {len(orphans)}")
    typec: dict[str, int] = {}
    for r in active:
        typec[r["type"]] = typec.get(r["type"], 0) + 1
    print("by type: " + (", ".join(f"{k}={v}" for k, v in sorted(typec.items())) or "\u2014"))
    tagc: dict[str, int] = {}
    for r in active:
        for t in r["tags"]:
            tagc[t] = tagc.get(t, 0) + 1
    print("by tag: " + (", ".join(f"{t}={c}" for t, c in sorted(tagc.items())) or "\u2014"))
    if active:
        oldest = min(active, key=lambda r: r["last_confirmed"] or "9")
        print(f"oldest active: {oldest['id']} (last_confirmed={oldest['last_confirmed']})")
    return 0


def cmd_supersede(args) -> int:
    active = _load_dir(ENTRIES)
    oldrow = _find(active, args.old)
    if not oldrow:
        print(f"error: active concept {args.old} not found", file=sys.stderr)
        return 1
    newrow = _find(active, args.new)
    if not newrow:
        print(f"error: active concept {args.new} not found", file=sys.stderr)
        return 1
    if oldrow["id"] == newrow["id"]:
        print("error: old and new are the same concept", file=sys.stderr)
        return 1
    ARCHIVE.mkdir(parents=True, exist_ok=True)
    dest = ARCHIVE / oldrow["file"].name
    oldrow["file"].rename(dest)
    newfm = dict(newrow["fm"])
    newfm["supersedes"] = oldrow["id"]
    newrow["file"].write_text(
        serialize_frontmatter(newfm) + "\n" + newrow["body"], encoding="utf-8"
    )
    _append_log(
        f"Archived [{oldrow['id']}](archive/{oldrow['file'].name}) \u2192 "
        f"superseded by [{newrow['id']}](entries/{newrow['id']}.md).",
        "Deprecation",
    )
    print(
        f"archived {oldrow['id']} \u2192 {dest.relative_to(ROOT)}; "
        f"{newrow['id']} supersedes it"
    )
    return cmd_rebuild(args)


def cmd_prune(args) -> int:
    active = _load_dir(ENTRIES)
    archived = _load_dir(ARCHIVE)
    ref = {r["supersedes"] for r in active if r["supersedes"]}
    orphans = [r for r in archived if r["id"] not in ref]
    if not orphans:
        print("no orphaned archive entries")
        return 0
    for r in orphans:
        rel = r["file"].relative_to(ROOT)
        if args.apply:
            r["file"].unlink()
            print(f"deleted {rel}")
        else:
            print(f"orphan {rel}  (use --apply to delete)")
    if args.apply:
        return cmd_rebuild(args)
    return 0


def cmd_query(args) -> int:
    kw = args.keyword.lower()
    scored = []
    for r in _load_dir(ENTRIES):
        score = 0
        if any(kw in t.lower() for t in r["triggers"]):
            score += 4
        if any(kw in t.lower() for t in r["tags"]):
            score += 3
        if kw in r["title"].lower():
            score += 2
        if kw in r["description"].lower():
            score += 1
        if score:
            scored.append((score, r))
    scored.sort(key=lambda x: -x[0])
    if not scored:
        print(f"no matches for {kw!r}")
        return 0
    for score, r in scored:
        print(f"--- {r['id']} (score={score}) {r['file'].relative_to(ROOT)} ---")
        print(f"# {r['title']}")
        print(r["description"])
        print()
    return 0


def cmd_log(args) -> int:
    _append_log(args.message, args.label)
    print(f"appended to {LOG.relative_to(ROOT)}")
    return 0


def _apply_root(root_arg: str) -> None:
    if not root_arg:
        return
    global ROOT, ENTRIES, ARCHIVE, INDEX, LOG
    ROOT = Path(root_arg).expanduser().resolve()
    ENTRIES = ROOT / "entries"
    ARCHIVE = ROOT / "archive"
    INDEX = ROOT / "index.md"
    LOG = ROOT / "log.md"


def main(argv=None) -> int:
    _common = argparse.ArgumentParser(add_help=False)
    _common.add_argument(
        "--root",
        default=None,
        help="memory root dir (default: <git-toplevel>/memory, else ./memory)",
    )

    ap = argparse.ArgumentParser(
        prog="memory.py", description="Memory store maintenance layer (OKF v0.1)."
    )
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("rebuild", parents=[_common], help="regenerate index.md (OKF §6 listing) from entries/ frontmatter")
    p.set_defaults(func=cmd_rebuild)

    p = sub.add_parser("add", parents=[_common], help="allocate next id and write a concept template")
    p.add_argument("--fix", action="store_true", help="type=correction; default decision")
    p.set_defaults(func=cmd_add)

    p = sub.add_parser("stale", parents=[_common], help="list concepts with last_confirmed older than N days")
    p.add_argument("days", type=int, nargs="?", default=STALE_DEFAULT_DAYS)
    p.set_defaults(func=cmd_stale)

    p = sub.add_parser("stats", parents=[_common], help="counts by type/tag, archive, orphans, oldest")
    p.set_defaults(func=cmd_stats)

    p = sub.add_parser("supersede", parents=[_common], help="archive <old>; mark <new> as superseding it; rebuild")
    p.add_argument("old")
    p.add_argument("new")
    p.set_defaults(func=cmd_supersede)

    p = sub.add_parser("prune", parents=[_common], help="list/delete archive entries referenced by no active concept")
    p.add_argument("--apply", action="store_true", help="delete orphans (default: dry-run)")
    p.set_defaults(func=cmd_prune)

    p = sub.add_parser("query", parents=[_common], help="scan frontmatter for keyword; print ranked descriptions")
    p.add_argument("keyword")
    p.set_defaults(func=cmd_query)

    p = sub.add_parser("log", parents=[_common], help="append a dated entry to log.md (OKF §7)")
    p.add_argument("message", help="log message text")
    p.add_argument("--label", default="Update", help="leading label, e.g. Creation/Update/Deprecation")
    p.set_defaults(func=cmd_log)

    ns = ap.parse_args(argv)
    _apply_root(ns.root)
    return ns.func(ns)


if __name__ == "__main__":
    sys.exit(main())
